version: '3.8'

services:
  fastapi:
    build: .
    command: fastapi dev main.py
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - my-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postg_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - /custom/mount:/var/lib/postgresql/data
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network
  
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    links: 
      - postgres:postgres  # my database container is called postgres, not db
    environment:
      - DATABASE_URL=postgres://user:pass@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network: